name: CI/CD for React Native with Expo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy Android APK
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.17.0

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: npm install

      # Step 4: Install Expo CLI
      - name: Install Expo CLI
        run: npm install -g expo-cli

      # Step 5: Login to Expo
      - name: Login to Expo
        run: expo login --access-token ${{ secrets.EXPO_TOKEN }}

      # Step 6: Build Android APK
      - name: Build Android APK
        run: npx expo build:android --no-wait

      # Step 7: Wait for Build to Complete
      - name: Wait for Build to Complete
        run: |
          npx expo build:status --platform android > build-status.json
          cat build-status.json

      # Step 8: Download APK
      - name: Download APK
        run: |
          BUILD_URL=$(jq -r '.artifacts[0].url' build-status.json)
          curl -o android.apk "$BUILD_URL"

      # Step 9: Upload APK to Repository
      - name: Upload APK to Build Folder
        run: |
          mkdir -p build/android
          mv android.apk build/android/
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add build/android/
          git commit -m "Deploy Android APK"
          git push origin main