name: Build and Deploy with EAS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step to checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step to set up Node.js for the project
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step to install dependencies
      - name: Install dependencies
        run: npm install

      # Step to install EAS CLI
      - name: Install EAS CLI
        run: npm install -g eas-cli

      # Set Expo token from GitHub Secrets to environment variable
      - name: Set Expo token
        run: echo "EXPO_TOKEN=${{ secrets.EXPO_TOKEN }}" >> $GITHUB_ENV

      # Run EAS Build for Android (APK)
      - name: Build with EAS (Android APK)
        run: eas build --platform android --profile androidapk --non-interactive

      # Wait for the build to finish and get the APK URL
      - name: Wait for build to finish and get APK URL
        run: |
          # Use EAS API to check build status
          BUILD_ID=$(eas build:list --status finished --json | jq -r '.[0].id') # Get the build ID of the latest completed build
          APK_URL=$(eas build:status $BUILD_ID --json | jq -r '.artifacts.buildUrl') # Get the APK download URL
          echo "APK URL: $APK_URL"
          curl -o build/android/app.apk $APK_URL # Download APK

      # Commit and push build to GitHub
      - name: Commit and push build to GitHub
        run: |
          git config --global user.name "AesthCy"
          git config --global user.email "geralddavin93@gmail.com"
          mkdir -p build/android
          cp build/android/app.apk build/android/
          git add build/android/app.apk
          git commit -m "Add APK build to build/android/"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
